# Generated by Django 2.2.5 on 2019-09-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
